spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MD4S8
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
app:
  upload-dir: ${user.dir}/uploads/